name: CI

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        libfranka-version: [ 0.9.2, 0.10.0 ]
    uses: ./.github/workflows/build_and_test.yml
    with:
      libfranka-version: ${{ matrix.libfranka-version }}
