name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential cmake git python-pybind11 libpoco-dev libeigen3-dev

        # Reflexxes
        git clone https://github.com/pantor/RMLTypeII.git
        cd RMLTypeII
        mkdir build
        cd build
        cmake ..
        make

        # Libfranka
        git clone --recursive https://github.com/frankaemika/libfranka.git
        cd libfranka
        git checkout 0.6.0
        git submodule update
        mkdir build
        cd build
        cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF ..
        make
        sudo make install

        # Catch2
        git clone https://github.com/catchorg/Catch2.git
        cd Catch2
        git checkout v2.5.0
        mkdir build
        cd build
        cmake -DCATCH_BUILD_TESTING=OFF -DCATCH_ENABLE_WERROR=OFF -DCATCH_INSTALL_DOCS=OFF -DCATCH_INSTALL_HELPERS=OFF ..
        make
        sudo make install


    - name: configure & make
      run: |
        mkdir -p build
        cd build
        cmake -DREFLEXXES_TYPE=ReflexxesTypeII -DReflexxes_ROOT_DIR=RMLTypeII/ -DReflexxes_LIB_DIR=RMLTypeII/build -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DPYTHON_LIBRARY=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.so ..
        make

    - name: test
      run: ./unit_test
